### ISSUE TITLE
React-native fs stops other async functions to execute until the file downloads

### ISSUE THREAD

**Issue by codesinghanoop** [johanneslumpe/react-native-fs#251]
I am using react-native fs to download the file. The react-native fs uses promises, so until the promise is returned back it keeps other async functions in a queue to execute. For instance, If i start downloading a file then other async functions(such as getting data from local storage) gets blocked. The other async function starts executing only when the download is complete.  

any help would be appreciated.

**Comment by codesinghanoop** [comment]
I found the solution to the issue, Adding few code to the android files will solve the above issue. I made new thread

**Comment by codesinghanoop** [comment]
can i contribute?

**Comment by johanneslumpe** [comment]
@codesinghanoop Feel free to! I cannot devote any time to this project at the moment but maybe @cjdell or other contributors can take a look at your PR.

**Comment by codesinghanoop** [comment]
@johanneslumpe @cjdell I have sent you the pull request, please go through it.

**Comment by aengl** [comment]
@codesinghanoop Had the same problem and tried your PR. Works like a charm! Thank you.

**Comment by codesinghanoop** [comment]
No problem friend. @johanneslumpe @cjdell please review my PR, it's helpful.

**Comment by br4nnigan** [comment]
is it possible that currently downloads block each other in that manner? That means only one download at a time. I have this impression but will investigate further.

**Comment by codesinghanoop** [comment]
No two parallel download will work. Second download will proceed after first download is done successfully.....

**Comment by itinance** [comment]
maybe we should start each download task in a separate thread?

**Comment by codesinghanoop** [comment]
@itinance Thanks for the reference sir..

**Comment by itinance** [comment]
If we would parallelize all download task with next release, some apps could get in trouble than maybe. For keeping backward compat i would suggest to add an optional separateThread-Mode. If this is true, the downloadTask would start in a separate thread, otherwise not.

**Comment by codesinghanoop** [comment]
Yes that's a good idea...

**Comment by codesinghanoop** [comment]
Hi guys, According to me we have to add a new thread to write the file and my research says that would not affect other things. We are basically adding thread only for writing the files.

**Comment by itinance** [comment]
And you use the code of your PR for this, right? https://github.com/itinance/react-native-fs/pull/254
Then i will speed it up in upcoming days to test and merge

**Comment by codesinghanoop** [comment]
Yes, sir..

**Comment by itinance** [comment]
Ok thank you! I will do the same on iOS side and merge it then together with your PR. Tomorrow or on Monday.

**Comment by codesinghanoop** [comment]
cool :)

**Comment by itinance** [comment]
I will merge this in upcoming days, together with a solution for iOS also by my own. Thought i could do this much faster but it will take some days.

**Comment by codesinghanoop** [comment]
Yeah, no problem ..Thank you :)

**Comment by a-koka** [comment]
Hi guys! Thanks for the research around this. It would be great to parallelize downloads.

@itinance, why do you think that parallelizing may cause issues on some devices?

**Comment by itinance** [comment]
Because multithreading is often a pain to debug. Anyway I just merged #254 for android. Need to do this also for iOS or someone wants to send a PR for it?

**Comment by pudility** [comment]
@itinance Has this been released yet? I am having the same issue when I use the `react-native-fs` npm module.

**Comment by codesinghanoop** [comment]
is it for iOS or Android ?

**Comment by pudility** [comment]
Android for now (but I am hoping to include iOS later)

**Comment by codesinghanoop** [comment]
I'm assuming you are using current version of this lib. Please can you install v2.5 and let me know you are still facing the same issue.

**Comment by pudility** [comment]
That fixed it! Thank you so much! Why is this not in the current version?

**Comment by codesinghanoop** [comment]
i don't know or may be some new functionality is destroying this. @itinance
